#!/bin/sh
# postrm script for <%= appname %>
#
# see: dh_installdeb(1)

set -e
case "$1" in
    upgrade|remove|purge)
        rm -rf /var/www/webapp/server/market/<%= uuid %>/
        rm -rf /var/www/webapp/public/assets/apps/<%= uuid %>/
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0